# Generated by Django 3.2.23 on 2023-12-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaande', '0007_auto_20231221_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
